// https://www.gimtec.io/articles/process-is-not-defined/

// Contract Addresses
const FIRE_ROCK_TOKEN = process.env.NEXT_PUBLIC_FIRE_ROCK_GOLD_ADDRESS;
const MULTI_SIG_ADDRESS = process.env.NEXT_PUBLIC_MULTISIG_ADDRESS;

// MultiSig Address
const OWNER_ADDRESS_1 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_1;
const OWNER_ADDRESS_2 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_2;
const OWNER_ADDRESS_3 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_3;
const OWNER_ADDRESS_4 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_4;
const OWNER_ADDRESS_5 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_5;
const OWNER_ADDRESS_6 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_6;
const OWNER_ADDRESS_7 = process.env.NEXT_PUBLIC_OWNER_ADDRESS_7;

// PolygonScan URL
const POLYGONSCAN_URL = process.env.NEXT_PUBLIC_POLYGONSCAN_URL;

// Alchemy Web Socket Provider
const ALCHEMY_WEB_SOCKET_PROVIDER =
  process.env.NEXT_PUBLIC_ALCHEMY_WEB_SOCKET_PROVIDER;

// Dummy Key
const DUMMY_KEY = process.env.NEXT_PUBLIC_DUMMY_KEY;

export const CONTRACT_ADDRESSES = {
  FIRE_ROCK_TOKEN,
  MULTI_SIG_ADDRESS,
  OWNER_ADDRESS_1,
  OWNER_ADDRESS_2,
  OWNER_ADDRESS_3,
  OWNER_ADDRESS_4,
  OWNER_ADDRESS_5,
  OWNER_ADDRESS_6,
  OWNER_ADDRESS_7,
};

const CONFIG = {
  ...CONTRACT_ADDRESSES,
  POLYGONSCAN_URL,
  ALCHEMY_WEB_SOCKET_PROVIDER,
  DUMMY_KEY,
};

export const ADDRESS_NAMES: Record<string, string> = {};

ADDRESS_NAMES[CONTRACT_ADDRESSES.FIRE_ROCK_TOKEN!] = "FireRock Token";
ADDRESS_NAMES[CONTRACT_ADDRESSES.MULTI_SIG_ADDRESS!] = "MultiSig Wallet";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_1!] = "Owner 1";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_2!] = "Owner 2";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_3!] = "Owner 3";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_4!] = "Owner 4";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_5!] = "Owner 5";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_6!] = "Owner 6";
ADDRESS_NAMES[CONTRACT_ADDRESSES.OWNER_ADDRESS_7!] = "Owner 7";

export default CONFIG;
